# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-20 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersistentObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(default=b'{}')),
            ],
        ),
        migrations.CreateModel(
            name='GamePersistentData',
            fields=[
                ('persistentobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chess_engine.PersistentObject')),
            ],
            bases=('chess_engine.persistentobject',),
        ),
    ]
