# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-19 07:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chess_engine', '0002_usercolorset'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRanking',
            fields=[
                ('persistentobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chess_engine.PersistentObject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('chess_engine.persistentobject',),
        ),
    ]
