# Generated by Django 5.0.1 on 2024-01-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_engine', '0003_userranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persistentobject',
            name='data',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='persistentobject',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
